GDSC-PKNU-Official/pknu-notice-front

src/components/Button/index.tsx, src/styles/Global/index.tsx, tsconfig.json
- Closes: #6 
- Button 컴포넌트 구현했어요. 일단은 디자인에 있는 컴포넌트만 고려했습니다.
- `width: 100%`로 줘서 아마 레이아웃 잡으면 그거에 맞게 들어갈거에요.
- disabled 속성 따로 안주면 enabled된 상태가 default에요.
```ts
const 예시 = () => {
const [count, setCount] = useState(0);
return (
<>
{count}
<div
css={css`
display: flex;
flex-direction: row;
`}
>
<Button onClick={() => setCount(count + 1)}>+1</Button>
<Button onClick={() => setCount(count - 1)}>-1</Button>
</div>
<Button disabled={count < 3}>hi</Button>
</>
);
};
```
https://user-images.githubusercontent.com/65100540/226532643-1c1963bf-f3f4-4e23-b404-7e1080ec1f63.mov
=> Feat/#6: Button 컴포넌트 구현

jest.config.js, src/@types/major.ts, src/components/MajorProvider/index.tsx, src/contexts/major.ts, src/hooks/useMajor.ts, src/main.tsx, src/pages/MajorDecision/index.test.tsx, src/pages/MajorDecision/index.tsx
* Closes: #49 
* 전공상태를 전역으로 관리하기 위한 Context 를 생성했어요.
~~이 pr 은 수정사항도 있고 일단 커밋이 많습니다..리뷰할 것도 많을 것 같아 미리 감사의 말씀을...ㅎㅎ~~
* components/`MajorProvider` 생성
- major 전역상태 내려주는 provider 컴포넌트 따로 만들기로 슬랙에서 얘기 했어서, 따로 components 폴더에 만들었어요.
* `useMajor` 커스텀 훅 생성
- useContext 를 통해서 내려받은 전역상태를 불러오는 로직을 커스텀 훅으로 빼는 것이 좋을 것 같아 `useMajor` 커스텀 훅을 만들었어요.
* 간단하게 전역 상태 설정하는 로직 구현
- 학과선택페이지에서 전역상태 `컴퓨터공학과` 설정하는 로직 한번 만들어 봤어요..테스트도 해볼겸..ㅎㅎ
* `jest.config.js` 파일에 @contexts 절대경로 폴더 추가
- jest 환경에서 @contexts 절대경로 폴더에 있는 context 들을 가져오기 위해서 설정을 추가해 줬어요.
* 브라우저 환경과 테스트 환경은 정말 다르다...
* 테스트 코드.. 빡세다
* 훅은 오직 함수형 컴포넌트 내부에서만 사용할 수 있다.
- 버튼을 클릭하면, 전역상태가 제대로 설정 되는지 확인하기 위해서 테스트 함수 `it` 내부에서 `useMajor` 커스텀 훅을 호출 했었는데요..에러를 뱉더군요
- 그래서 `span` 태그에 `note` 라는 role을 주고 이를 통해서 테스트 환경에 가져와서 상태가 제대로 변경 되는지 확인하는 로직으로 변경했습니다.
* moking..! …
=> Feat/#49: 전공상태 전역으로 관리하기 위한 Context 생성

src/components/Card/AnnounceCard/index.test.tsx, src/components/Card/AnnounceCard/index.tsx
* Closes : #38 
* 공지사항 카드 컴포넌트 구현 했어요.
* 아직 크롤링을 통한 데이터를 가져올 수 있는 서버 측 로직이 없기 때문에 네이버 기사 하나 가져와서 구현했어요.
* 앱 내부 url 이동이라면, `routerTo` 함수를 사용했겠지만 앱 외부 url 이동이기 때문에 `window.location.href` 를 사용 했어요.
* Figma 에서 두 줄만 내용이 채워져 있어서 내용이 최대 두줄 까지만 나오도록 했어요.
* 테스트 코드 작성 때, 했던 고민은 [여기](https://paper-mass-5ff.notion.site/4-30-e42ab08143814ed6bf39c9c0ee6d991c) 서 확인할 수 있어요.
=> Feat/#38: 공지사항 카드 컴포넌트 구현

src/@types/styles/icon.ts, src/components/Icon/index.tsx, src/components/Modal/MajorModal/index.tsx, src/components/Modal/SuggestionModal/index.tsx, src/components/Modal/index.tsx, src/pages/My/index.test.tsx, src/pages/My/index.tsx, src/utils/styles/textarea-resize.ts
* Closes: #72 
* 마이페이지를 구현 했어요
* 모달 창에서 padding 사이즈가 너무 큰 것 같아서 `50px -> 30px` 로 변경했어요, 
* 모달 창과 같은 스타일 관련 이슈들은 배포 시점에 **모바일 환경을 고려한 디자인을 고민하는 시점**에 다시 얘기 해봐야할 것 같아요
* 모달 창 2개의 사이즈를 통일 하는것이 좋다고 판단해 `width: 80%` 로 고정했어요.
* 건의사항 textarea 의 세로칸 증가에 대하여
* 사용자가 설정해둔 textarea 의 가로 길이를 벗어나는 경우
* 사용자가 줄바꿈을 강제로 하는 경우
* 위의 2가지 경우에 대해서 textarea 의 세로칸을 1칸 증가 해줘야 했어요, 기본 textarea 는 이 기능이 자동으로 되지 않고 스크롤바를 통해서 세로로 이동할 수 있도록 하는 기능밖에 없어요
```typescript
export function areaResize(area: HTMLTextAreaElement) {
area.style.height = 'auto';
area.style.height = `${area.scrollHeight - 20}px`;
area.style.lineHeight = '1.5';
}
```
* 현재 textarea 의 스크롤 높이에 따라서 `height` 의 값을 계속 업데이트 해줘야 했어요
https://github.com/hwinkr/algorithm/assets/68489467/534b25f8-103d-4a40-95d8-facdc661b11b
* msw 를 사용해서 브라우저 환경에서 notion api 동작을 테스트 …
=> Feat/#72: 마이페이지 구현

src/apis/Suspense/fetch-announce-list.ts, src/apis/Suspense/wrap-promise.ts, src/components/Card/AnnounceCard/AnnounceList/index.tsx, src/components/Card/AnnounceCard/Skeleton.tsx, src/components/Card/AnnounceCard/index.tsx, src/styles/Skeleton/SkeletonItem.ts
* Closes: #76 
* Suspense + Skeleton UI 를 구현했어요
* 자세한 구현방법, 구현을 위해 했던 고민들은 `부림이 기술 블로그` 에 작성 해놓을게요.(아직 작성 안함..ㅎ)
```typescript
const AnnounceList = lazy(
() => import('@components/Card/AnnounceCard/AnnounceList'),
);
const Announcement = () => {
const { major } = useMajor();
return (
<>
<Suspense fallback={<AnnounceCardSkeleton length={3} />}>
<AnnounceList resource={fetchAnnounceList(major)} />
</Suspense>
</>
);
};
```
* `<AnnounceCardSkeleton length={3} />` 에서, `length={3}` 을 통해 몇개의 Skeleton UI 를 렌더링 할 것인지 미리 알 수 있도록 해줘야 해요.
* Skeleton UI 를 적용할 컴포넌트를 Suspense 의 자식 컴포넌트로 지정해주면 돼요!
* 자식 컴포넌트 내부에서는 Suspense 가 비동기 요청 프로미스의 현재 상태를 알 수 있도록 해줘야 해요(**주로 read 함수를 통해 구현**)
```typescript
const AnnounceList = ({ resource }: AnnounceListProps) => {
const announceList: Resource = resource.read(); …
```
=> Feat/#76: Suspense 적용

docker-compose.prod.yml, dockerfile.prod, nginx/proxy/default.conf, nginx/proxy/dockerfile, nginx/static/default.conf
- closes: #82 
- nginx 를 프록시와 정적 파일 제공하는 기능을 하나로 구성하려 했는데 구성에 어려움이 있어서 따로 구성했어요
- dockerfile 과 docker-compose 파일의 경우 개발환경과 배포환경을 따로 구성했어요 !
- 그리고 백엔드 URL 이 없기에 프론트엔드 URL 로 설정해뒀어요
- 기존 개발환경은 그대로 `docker-compose up` 하면은 간단하게 동작할 수 있어요
- 배포 환경에서는 `docker-compose -f docker-compose.prod.yml up` 을 이용해서 실행해야 해요 (파일 이름을 명시해줘야해요)
- 배포환경을 실행해보면 에러가날 수 있어요. 그 이유는 내 파일을 그대로 도커 컨테이너에 복사하여 실행하는데 이때 node_modules 에 문제가 있어요
- 그 이유는 node_modules 는 package.json, yarn-lock.json 을 보고 내 환경에 맞게 모듈들을 설치하는데 내 로컬에 맞는 node_modules 를 도커 컨테이너로 복사해가서 사용하기에 에러가 발생해요
- 간단하게 local 에 있는 node_modules 를 삭제하고 도커 컴포즈를 실행하면 돼요
1. 일단 클라이언트가 우리 앱(URL)에 접속해요 (http://localhost:5173)
2. 그러면 바로 우리 서버를 만나는게 아니라 프록시(nginx) 를 만나게 돼요. 그럼 프록시는 pathname 을 보고 /api 로 시작하면 백엔드 주소로 보내고 그게 아니라면 클라이언트로 보내게 돼요
3. 클라이언트로 보내게 된다면 클라이언트에 있는 정적 파일 …
=> Config/#82: nginx 구성

src/apis/Suspense/fetch-announce-list.ts, src/components/Card/AnnounceCard/index.test.tsx, src/components/List/CollegeList/index.tsx, src/components/List/DepartmentList/index.tsx, src/config/index.ts, src/mocks/handlers/announceHandlers.ts, src/mocks/handlers/majorHandlers.ts
- config 파일에서 백엔드 주소를 직접 적어줬어요. (.env 파일에서 값을 가져오게 설정하려면 추가적으로 고려해야해요)
- 모든 api 요청 주소를 /api 로 시작하도록 변경했어요
=> Refactor/#86: 배포된 백엔드와 통신되도록 엔드포인트 변경

src/@types/announcement.ts, src/components/Card/AnnounceCard/index.test.tsx, src/components/Card/AnnounceCard/index.tsx
* Closes: #99 
* 백엔드 공지사항 데이터와 스키마 통일했어요.
* AnnounceCard가 받는 props를 수정해 외부 링크로 이동할 수 있게 했어요.
=> Chore/#99: 백엔드 공지사항 데이터와 스키마 통일

.env.vault, index.html, src/App.tsx, src/components/FooterTab/index.tsx, src/components/Header/index.tsx, src/components/Modal/MapBoundsLimitModal/index.tsx, src/components/Modal/MapLevelLimitModal/index.tsx, src/constants/pknu-map.ts, src/pages/Map/MapLevelObserver.tsx, src/pages/Map/MapboundaryObserver.tsx, src/pages/Map/PknuBuildingNumbers.tsx, src/pages/Map/index.tsx
* Closes: #93 
* 지도 페이지 구현했어요
* 카카오 지도 API
* index.html 파일의 script 태그를 통해서 카카오지도를 사용하기 위한 API_KEY를 환경변수를 사용해서 등록했어요.
* 설저해놓은 축소레벨, 지도의 범위를 벗어나게 되면 경고 모달창을 렌더링 하고 사용자를 기본위치로 다시 이동시켜요. 확대레벨 제한은 없어요
* 사용자의 위치는 보안상의 이유로 https 환경에서만 설정이 가능해요. 따라서, http 환경인 로컬서버에서는 위치를 확인할 수 없어서 개발하는데 제한이 있었어요. 따라서 일단 사용자의 위치 렌더링은 보류 했어요.
* 번들러에 따라서 환경변수 설정법이 다르다
* vite, cra등의 번들러마다 환경변수 설정법이 다르기 때문에, 번들러 환경에 따라서 환경변수 설정을 다르게 해줘야 한다는 것을 배웠어요.
* 개발이 진행됨에 따라 모달을 사용하는 컴포넌트가 꽤 많아지는데, 모달의 렌더링 상태를 전역상태로 관리하는게 더 괜찮을 것 같아요.
https://github.com/hwinkr/algorithm/assets/68489467/744de551-f54d-484a-ba3b-15b9785b4d5f
https://github.com/hwinkr/algorithm/assets/68489467/5d409274-6aac-43fa-991b-112e2ff3520d
=> Feat/#93: 지도 페이지 구현

src/components/List/DepartmentList/index.test.tsx, src/components/List/DepartmentList/index.tsx, src/mocks/handlers/majorHandlers.ts
- Closes: #102 
- 공지사항 선택 시 학부/학과, 전공이 모두 있는 학과는 전공값만 로컬 스토리지에 저장하여 사용하도록 수정했어요 (서버에서 그렇게 처리하기 때문이에요)
- 예를들어 `조형학부 건축학전공` 인 경우 `건축학전공` 으로 저장하도록 변경했어요!
=> Fix/#102: 공지사항 선택 시 특정 학과는 공지 안보이는 에러 수정

src/@types/modals.ts, src/@types/styles/icon.ts, src/components/Card/InformCard/index.test.tsx, src/components/Card/InformCard/index.tsx, src/components/Icon/index.tsx, src/components/List/DepartmentList/index.test.tsx, src/components/List/DepartmentList/index.tsx, src/components/Modal/AlertModal/index.tsx, src/components/Modal/ConfirmModal/index.tsx, src/components/Modal/Modals/index.tsx, src/components/Modal/SuggestionModal/index.tsx, src/components/Modal/index.tsx, src/components/ModalsProvider/index.tsx, src/constants/modal-messages.ts, src/contexts/modals.ts, src/hooks/useModals.ts, src/main.tsx, src/pages/Announcement/index.tsx, src/pages/Home/Home.test.tsx, src/pages/My/index.test.tsx, src/pages/My/index.tsx
* Closes : #105 
* 건의사항을 작성하고 사용자가 보내기 버튼을 누르기 전, 보낸 내용에 대해서 한번더 확인하는 모달을 구현했어요
* 개발이 진행됨에 따라, 모달을 사용하는 컴포넌트가 많아져서 각 컴포넌트가 모달의 상태를 가지고 있는게 비효율적이라고 판단했고 따라서 모달의 상태를 전역으로 빼기로 결정했어요
* 전역으로 관리 할 모달의 상태
* boolean값을 사용해서 모달의 상태를 관리하려고 했으나, 이 방법을 사용하면 한 모달이 렌더링 되면 모든 모달이 렌더링 되는 문제가 발생해요
* 전역으로 관리 하는 모달의 상태는 객체 배열이에요.
```typescript
const 모달전역상태 = [
{
Component: // something....
props: // something...
},
{
//...
}
]
```
* modals - 객체 배열 / setModals: 객체 배열을 수정할 수 있는 함수
* 모달의 표준화
* 앱 내부에서 사용하는 모달을 표준화 했어요
* 크게 보면 경고, 확인, 건의사항전송 모달이 필요해서 각 컴포넌트를 추상화 하고 사용할 때 사용자에게 전달할 메세지와 함수를 주입할 수 있도록 했어요
* useModals 훅
* 코드 
```typescript
const useModals = () => {
//...
const openModal = useCallback(
<T extends FunctionComponent<any>>(
Component: T,
props: Omit<ComponentProps<T>, 'open'>,
) => {
setModals((modals) …
```
=> Feat/#105: 건의사항 작성 시 한번더 확인하기 구현 & 모달 전역상태로 변경

src/components/List/DepartmentList/index.test.tsx, src/components/List/DepartmentList/index.tsx
- closes: #109 
- 학부/학과와 전공 모두 있는경우 전공만 저장하도록 수정했어요
- 테스트코드의 경우 모달창에 확인을 누른경우 함수가 실행되어야는데 모달(useModals)을 모킹했기 때문에 테스트가 안되어 skip으로 바꿨어요!
=> Fix: 학부/학과와 전공 모두 있는경우 전공만 저장하도록 수정

src/App.tsx, src/components/Button/index.tsx, src/components/Card/InformCard/index.test.tsx, src/components/Card/InformCard/index.tsx, src/mocks/handlers/announceHandlers.ts, src/pages/Announcement/index.tsx, src/pages/Home/index.tsx
* 공지사항 페이지 내부에서 학교, 학과 공지사항을 분리해서 보여줄 수 있도록 했어요
* `announceKeyword`를 사용해서, 비동기 데이터를 가져와요
* 이렇게 한 이유는 state 사용할 경우 새로고침할 경우 문제가 생기고(앱이라서 새로고침 할 일은 없겠지만,,,) 
* `setState` 호출로 인해서 불필요한 리렌더링도 발생할 수 있기 때문에, URL을 파싱하기로 했어요.
* 현재 사용자가 보고 있는 공지사항을 강조해주기 위해서 기존에 사용중이던 `Button` 컴포넌트에 스타일을 외부에서 주입할 수 있도록 변경했어요.
* 프로토타입을 작성할 때, 피그마에서는 버튼의 배경색이 아닌 css `border`의 `bottom-line`을 통해서 강조했어요.
* 하지만, 개발을 시작하고 나서 버튼의 배경색을 GREEN으로 고정했고 고정된 배경색을 사용중인 컴포넌트도 너무 많아서 지금 배경색을 외부에서 주입하도록 변경하기에는 오버헤드가 너무 클 것 같다는 판단을 했어요.
* 따라서, 버튼의 배경색을 변경해야 하는 경우에만 외부에서 주입하도록 하기 위해서`ButtonHTMLAttributes<HTMLButtonElement>`이 타입을 확장해서 Button 컴포넌트의 prop을 재정의 했어요!
* informCard 컴포넌트에 추가된 `majorRequired` prop
* 학교 공지사항은 전공이 선택되지 않아도 보여주기로 결정했고, 따라서 공지사항 페이지 자체는 전공 선택되지 않아도 방문할 수 있도록 해야 했어요.
* 따라서, 졸업요건 카드만 전공을 선택해야 사용할 수 있도록 해야 했는데 전공이 …
=> Feat/#112: 공지사항 페이지에서 학교, 학과 공지사항을 분리해서 보여줄 수 있는 UI 구현

src/components/Icon/index.tsx, src/components/List/CollegeList/index.tsx, src/components/List/DepartmentList/index.tsx
- closes: #113
- 단과대/학과 선택 UI 개선했어요
- #115에 대응해서 만들었기에 모두 합쳐보고 추가로 수정하는게 좋을거 같아요!
- #115에 대응해서 만들었기에 현재 이미지에 Footer쪽에 부자연스러운 부분이 있어요
- 버튼이 여러개 클릭된거는 학과 이름이 같아서 div 키 값이 같아서 여러개 선택되어 있어요..
=> Style/#113: 단과대/학과 선택 UI 개선

src/@types/announcement.ts, src/@types/styles/icon.ts, src/components/Card/AnnounceCard/AnnounceList/index.tsx, src/components/Card/AnnounceCard/index.test.tsx, src/components/Card/AnnounceCard/index.tsx, src/components/Icon/index.tsx, src/mocks/handlers/announceHandlers.ts
* 공지사항 고정, 일반 구분 UI 구현했어요
* 확성기 아이콘 사용해서 구분해요
* 서버에서 객체 형태로 데이터를 넘겨주고 키를 사용해서 고정, 일반 구분해요
=> Feat/#117: 공지사항 고정, 일반 구분 UI 구현

src/App.tsx, src/components/Header/index.tsx
- closes: #130 
- 헤더 크기를 줄였어요!
- 헤더 중간에 LOGO에서 BURIMI 로 바꿨어요
--before--
--after--
=> Fix: 헤더 padding 크기 변경

src/components/List/DepartmentList/index.tsx
- closes: #132 
- 학과 선택하는 버튼 아래로 배치했어요
아래와 같이 버튼까지 콘텐츠가 안내려가도록 수정했어요!
=> Fix: 학과 선택하는 버튼 아래로 배치

index.html
- closes: #134 
- 모바일에서 확대 안되도록 수정했어요
- 다만 카카오맵에서는 확대 및 축소가 가능한것을 확인했어요
=> Fix: 모바일에서 확대 안되도록 수정

src/App.tsx, src/components/FooterTab/index.tsx, src/components/Header/index.tsx
- closes: #138 
- 헤더, 푸터 높이 단위 vh 로 변경했어요
=> Fix: 헤더, 푸터 높이 단위 vh 로 변경

src/components/Card/AnnounceCard/index.tsx
- closes: #149 
- 외부링크 이동 시 인앱 브라우저가 아닌 외부 브라우저로 열리도록 수정했어요
=> Fix: 외부링크 이동 시 인앱 브라우저가 아닌 외부 브라우저로 열리도록 수정

src/mocks/handlers/graudationHandler.ts, src/pages/Home/index.tsx
- closes : #152 
- 서버와 졸업요건 데이터 스키마를 통일했어요.
=> Chore: 서버와 졸업요건 데이터 스키마 통일

src/App.tsx
- closes: #156 
- Body의 높이 설정 안하는걸로 롤백했어요
- header, footer 의 높이는 8vh 이고 콘텐츠의 상단 하단 공백을 여유분을 추가하여 8.5vh 로 padding 설정했어요
=> Fix: Body의 높이 설정 안하는걸로 롤백

src/components/Card/InformCard/index.tsx, src/components/FooterTab/index.tsx, src/components/Header/index.tsx, src/pages/Home/index.tsx, src/styles/Global/index.tsx
- closes: #159 
- 헤더 푸터 그림자 추가했어요
- 배경색을 완전 흰색이 아니라 노란 흰색으로 바꿨어요
=> Style/#159: 헤더 푸터 그림자 추가

public/manifest.json, public/sw.js, src/components/Button/Toggle/index.tsx, src/components/List/DepartmentList/index.tsx, src/hooks/urlBase64ToUint8Array.ts, src/mocks/browser.ts, src/mocks/handlers/subscribeHandler.ts, src/mocks/server.ts, src/pages/My/index.test.tsx, src/pages/My/index.tsx, src/styles/Global/index.tsx, vite.config.ts
- closes: #161 
- 알림 허용 시 서비스워커에서 알림을 받을 수 있도록 기능을 추가했어요
- 마이페이지 디자인을 개선했어요!
- 일단 학과 공지사항 알림만 할 수 있도록 추가했어요
- 만약 학과 공지사항 알림이 잘 된다면 학교 공지사항 알림도 쉽게 추가할 수 있을거 같아요!
- 만약 새로운 공지사항이 올라왔으면 올라온 모든 공지사항을 알림으로 보낼건지, 아니면 새로운 공지가 있다고 알림 1개만 보낼 지 고민해봐야할거 같아요 
- PWA 는 웹 브라우저에서 돌아가기 때문에 만약 사용자가 웹 브라우저의 알림을 껐다면 알림을 받을 수 없어요..
- 마이페이지 하단에 알림을 받을 수 있는 가이드라인을 하나 만들어야할 것 같아요
- 알림을 받는 방법은 추후 부리미 기술 블로그에 상세히 작성해둘게요!
=> Feat/#161: 알림 받을 수 있도록 기능 추가 & 마이페이지 디자인 개선

src/components/Modal/SuggestionModal/index.tsx, src/components/Modal/index.tsx
- closes: #189 
- 모달창의 가로크기도 최대 480px 로 설정했어요
- 세로 크기를 뷰포트의 60%로 설정해서 overflow되면 scroll 되게 수정했어요
- 회신받을 이메일 입력하는 공간은 지금 필요하지 않을거 같아서 추가하지 않았어요.. 나중에 필요하면 추가할게요 (추가할려고 했는데 UI가 안예뻐요..)
=> Fix/#189: 모달창 크기 수정

src/components/Card/AnnounceCard/Skeleton.tsx, src/components/Card/AnnounceCard/index.tsx, src/pages/Announcement/index.tsx
- closes : #166 
- 공지사항 페이지 디자인을 수정했어요
- 공지사항 제목이 1줄만 나오도록 설정하고, 모바일 기준 font-sizer가 너무 큰 것 같아서 조금 줄였어요
- 슬라이드 애니메이션을 적용하긴 했는데 데스크탑 환경에서는 화면 영역을 벗어난곳에서 애니메이션이 시작되어서 이상하지만, 모바일 환경에서는 괜찮은 것 같아요
- 고정이 아닌 일반 공지사항도 고정아이콘 speaker만큼 margin-left를 두긴 했는데 이상하면 화면 제일 왼쪽에 붙여버려도 괜찮을 것 같아요
https://github.com/GDSC-PKNU-21-22/pknu-notice-front/assets/68489467/231fa3be-1d11-42bd-a46d-b59cb1c5ad35
=> Style/#166: 공지사항 페이지 디자인 개선

jest.config.js, package.json, src/components/Card/InformCard/index.tsx, src/components/Carousel/index.tsx, src/constants/carouselInfo.ts, src/jest.setup.ts, src/pages/Home/index.tsx, yarn.lock
- closes: #84 
- 바뀐 홈 화면과 같은 방식으로 캐러셀을 추가했어요
- 현재 캐러셀의 내용은 서버에서 가져오는 것이 아닌 하드코딩 되어있어요!
--PC 화면--
--모바일 화면--
=> Feat/#84: 홈 화면에 캐러셀 추가

src/components/List/CollegeList/CollegeItem.tsx, src/components/List/CollegeList/index.tsx, src/components/List/DepartmentList/DepartmentItem.tsx, src/components/List/DepartmentList/index.tsx, src/components/List/Skeleton/college.tsx, src/components/List/Skeleton/department.tsx, src/pages/Announcement/index.tsx
- closes : #203 
- 학과 -> 학교 애니메이션 발생 후, 모바일 뷰포트가 커졌던 스타일 버그를 해결했어요
- 페이지에서 가장 최상위 부모 `div`에 `overflow-x:hidden`을 걸어서 해결했어요
- 단과대 선택 페이지에서 뷰포트가 움직였던 버그를 해결했어요
- `padding` 관련 문제라 크기를 줄였어요
- 학과 선택 페이지에서 선택완료 버튼 뒤에 학과가 있던 스타일 버그를 해결했어요
=> Fix/#203: 공지사항, 학과선택 페이지 스타일 버그 수정

public/manifest.json, src/components/Header/index.tsx
- closes: #207 
- 헤더 burimi를 한글 부림이로 변경했어요
- 부림이를 헤더 정 중앙에 배치하도록 했어요
- 한글이 이쁜지 영어가 이쁜지는 잘 모르겠어요.. ㅎㅎ
--before--
--after--
=> Fix/#207: 부리미 -> 부림이로 롤백 및 헤더 수정

src/components/Carousel/index.tsx
- closes: #211 
- 캐러셀 클릭 시 웨일비 홈화면으로 이동하도록 수정했어요
=> Fix: 캐러셀 클릭 시 웨일비 홈으로 이동하도록 변경

public/sw.js
- push 알림 클릭 시 본인 학과 공지사항 페이지로 이동하도록 추가했어요
- 대신 아래 스크린샷과 같이 바로 URL 을 통해 들어가니까 border-bottom 에러가 있어요
- 어떻게 border-bottom 이 설정되어있는지 몰라서 수정은 못했어요
=> Feat: push 알림 클릭 시 본인 학과 공지사항 페이지로 이동하도록 추가

src/@types/modals.ts, src/components/Card/InformCard/index.test.tsx, src/components/Card/InformCard/index.tsx, src/components/List/DepartmentList/DepartmentItem.tsx, src/components/Modal/Modals/index.tsx, src/components/Modal/SuggestionModal/index.tsx, src/components/ModalsProvider/index.tsx, src/constants/modal-messages.ts, src/contexts/modals.ts, src/hooks/useLocationHandler.ts, src/hooks/useModals.ts, src/pages/Announcement/index.tsx, src/pages/Map/components/MapHeader.tsx, src/pages/Map/handlers/limit-handler.ts, src/pages/Map/handlers/overlay-handler.ts, src/pages/My/index.test.tsx, src/pages/My/index.tsx
- closes : #222 
- 모달 state, dispatch 컨텍스트를 분리 했어요
> 지도 페이지에서, 길찾기 기능을 사용하기 위해서 건물 번호를 클릭하는 경우 지도 페이지 전체가 리렌더링되는 문제가 발생했어요. 지도 페이지 위에 있는 건물 번호를 클릭했을 때 실행되는 이벤트 핸들러 함수는 모달의 렌더링 상태만 변경(openModal)하는 책임만 있는데 이 함수가 호출됨으로 인해서 이 책임과는 상관없는 지도 페이지 전체가 리렌더링 되는것은 굉장히 비효율적이라고 판단했어요. 추가로, 지도 페이지에서 보여주는 UI도 많고 이벤트도 많고, 상태도 적지 않기 때문에 context를 분리해줘야 겠다는 판단을 했어요!
1. 컨텍스트의 분리
```ts
// pknu-notice-front/src/contexts/modals.ts
type Dispatch = React.Dispatch<SetStateAction<Modals>>;
const ModalState = createContext<Modals | null>(null);
const ModalDispatch = createContext<Dispatch | null>(null);
const ModalContext = {
ModalState,
ModalDispatch,
};
```
- 모달의 렌더링만 담당하는 컴포넌트에서는 ModalState 컨텍스트 사용
```ts
// pknu-notice-front/src/components/Modal/Modals/index.tsx
const Modals = () => {
const modals = …
```
=> Refactor/#210: 모달 state, dispatch 컨텍스트 분리

src/components/FooterTab/index.tsx, src/components/List/DepartmentList/DepartmentItem.tsx, src/pages/Announcement/index.tsx, src/pages/BodyLayout/index.tsx, src/pages/Map/index.tsx
- FooterTab 높이를 증가 시켰습니다
- [apple human interface](https://developer.apple.com/design/human-interface-guidelines)를 참고하려고 했는데, Tab내부에서 사용해야 할 아이콘의 적절한 크기 및 어떤 상황에서 어떻게 사용하면 좋을지에 대한 지침만 있어서 [PWA Today](https://whatpwacando.today/)참고해서 스타일을 변경했어요
- 변경 전
- 변경 후
=> Style/#224: FooterTab 높이 증가

src/components/Carousel/index.tsx, src/mocks/handlers/announceHandlers.ts, src/pages/Home/index.tsx
- closes: #226 
- 캐러셀 하드코딩 -> 서버에서 데이터를 가져와서 보여주도록 수정했어요
- 캐러셀 클릭을 유도할 수 있는 버튼 추가했어요
=> Refactor/#226: 캐러셀 리팩토링 

src/components/Modal/ConfirmModal/index.tsx, src/constants/modal-messages.ts, src/pages/My/index.tsx
- closes: #245 
- 알림 설정하기 전 모달창을 통해 몇시에 어떤 정보를 전해주는지 알려주도록 추가했어요
- 알림 설정이 실패 시 설정 실패 모달과 함께 노션 건의사항에 전송하도록 추가했어요
https://github.com/GDSC-PKNU-21-22/pknu-notice-front/assets/71641127/7f0d8ce2-6ad7-462d-8c77-60566e56e766
=> Feat/#245: 알림 설정에 모달창으로 정보 추가

public/.well-known/assetlinks.json
- closes: #251 
- 현재 안드로이드의 play store 로 받은 부림이의 경우 chrome 엔진 기반으로 열리면 URL 이 보이는 문제가 있어요
- 그 이유는 TWA 라고 해서 chrome 에서 우리 앱을 제대로 신뢰하지 않기에 그렇다고 해요
- 그래서 https://<YOUR-PWA-URL>/.well-known/assetlinks.json 주소에 TWA 정보를 입력해 둬야해요
- 여기서 추가한 점은 google play console 의 부림이 앱의 설정 -> 앱 서명의 SHA-256 인증서 지문값을 추가해줬어요
- 자세한 사항은 아래에서 확인할 수 있어요
https://docs.pwabuilder.com/#/builder/asset-links-faq?id=removing-the-browser-address-bar
=> Fix: google play console 의 fingerprints 값 추가

src/pages/My/index.tsx
- closes: #254 
- 'PushManager' in window 코드가 문제가 ios 쪽에 문제가 있는거 같아 제거했어요
=> Fix: 'PushManager' in window 코드 제거

src/@types/announcement.ts, src/components/Card/AnnounceCard/AnnounceList/index.tsx, src/components/Card/AnnounceCard/index.test.tsx, src/components/Card/AnnounceCard/index.tsx, src/components/Card/InformCard/index.test.tsx, src/components/Card/InformCard/index.tsx, src/components/Carousel/index.tsx, src/components/List/DepartmentList/index.test.tsx, src/components/MajorProvider/index.tsx, src/components/Modal/ConfirmModal/index.tsx, src/constants/announcement.ts, src/constants/path.ts, src/constants/placeholder-message.ts, src/constants/toast-message.ts, src/contexts/major.ts, src/pages/Announcement/components/AnnounceContainer.tsx, src/pages/Announcement/components/AnnounceNotFound.tsx, src/pages/Announcement/components/AnnounceSearch.tsx, src/pages/Announcement/components/AnnounceSearchList.tsx, src/pages/Announcement/components/AnnounceTypeButtons.tsx, src/pages/Announcement/components/index.ts, src/pages/Announcement/index.tsx, src/pages/Home/Home.test.tsx, src/pages/Home/components/InformCardList.tsx, src/pages/Home/index.tsx, src/pages/MajorDecision/index.test.tsx, src/utils/router/openLink.ts
- 공지사항 리스트 UI를 수정했어요
- 공지사항 검색 기능을 추가했어요
> 기존의 공지사항 페이지는 공지사항 페이지 내부에서 학교, 학과 공지사항을 나누어서 보여줬고 일반,  고정 공지사항은 확성기 아이콘을 통해서 구분하고 스크롤을 통해서 아래로 내려가야만 일반 공지사항을 확인할 수 있었어요. 만약, 알림이 왔을 때 해당 공지사항이 일반 공지사항이라면 사용자가 확인하기 위해서 아래로 내려가야 하고, 고정 공지사항의 양에 비례해서 스크롤도 많아지므로 불편함으로 이어질 수 있겠다고 생각했어요. 따라서 홈페이지에서 학교, 학과 공지사항을 구분하고 **각 공지사항 페이지 내부에서 일반, 고정 공지사항을 버튼으로 구분**하기로 했어요. 그리고, 공지사항 검색 기능도 추가 했어요
- 일반, 고정 공지사항 구분 예시
- 일반 : `/announcement/school/normal`
- 고정 : `/announcement/school/pinned`
- 검색 공지사항 예시
- 검색 : `/announcement/school/search?q=프로그래밍`
검색을 하면 url이 변경되고 컴포넌트가 리렌더링 되어서 api 호출 하는 코드도 한번 더 실행되는 문제가 있었어요. 이미 가져온 데이터에 검색 키워드가 있는지 확인하는데, url을 변경하다보니 불필요한 api 호출을 하기 때문에 `useMemo`를 활용해서 컴포넌트가 처음 렌더링 될 때만 api 호출을 하도록 했어요
<div> 
</ div>
=> Style/#273: 공지사항 리스트 UI 변경

src/components/Carousel/index.tsx
- closes: #290 
- 웨일비 캐러셀에 모집기관과 운영기간을 나눠서 보여주도록 변경했어요
=> fix(Carousel): 웨일비 캐러셀에 모집기관과 운영기간을 나눠서 보여주도록 변경

src/App.tsx, src/apis/suggestion/post-suggestion.ts, src/pages/Suggestion/index.tsx
- closes : #298
- 건의사항 페이지를 구현했어요
- #293 이 반영되지 않아서 나중에 머지되면 모달은 합성 컴포넌트로 변경해야돼요
=> feat/#294 : 건의사항 페이지 구현

src/@types/styles/icon.ts, src/apis/Suspense/fetch-announce-list.ts, src/components/Common/Icon/index.tsx, src/components/InformUpperLayout/InformSearchForm.tsx, src/constants/announcement.ts, src/constants/path.ts, src/constants/tip.ts, src/pages/Announcement/components/AnnounceContainer.tsx, src/pages/Announcement/index.tsx, src/pages/Home/components/InformHalfCard.tsx, src/pages/Home/components/InformHalfCardList.tsx, src/pages/Home/index.tsx, src/styles/ThemeProvider/theme.ts, src/styles/emotion.d.ts
- closes: #264 
- 어학 공지사항, 채용 공지사항의 카드 컴포넌트를 추가했어요
- 어학 공지사항은 확인이 가능하지만 채용 공지사항은 아직 에러가 발생해요
- 기존에 공지사항을 서버에 요청하는 방식을 일부 수정했어요 (이전에는 학과가 있는지 없는지 매개변수로 넘겨줬다면 현재는 엔드포인트값을 직접 넘겨주도록 변경했어요)
- 나중에 작업할 채용 공지사항의 경우 업로드 날짜가 아닌 채용 기간을 보여주기에 해당 사항도 일부 수정할 필요가 있어보여요!
=> Feat/#264: 어학 공지사항 기능 추가

src/pages/Suggestion/index.tsx
- 건의사항을 보낼 때 한번 더 내용을 확인하는 로직 추가
- closes : #300 
- 건의사항에서 사용하는 모달을 합성 컴포넌트로 변경했어요.
- 건의사항을 보내기 전에 한번더 내용을 확인하는 모달을 띄우는 것으로 유지하기로 했어요.
=> chore/#300 : 건의사항 페이지에서 사용하는 모달을 합성 컴포넌트로 변경

src/components/Card/AnnounceCard/index.tsx, src/pages/Announcement/index.tsx
- closes: #306 
- 채용 공지사항을 볼 수 있도록 기능을 추가했어요
- 채용 공지사항의 경우 업로드 날짜가 아닌 채용 기간을 보여주고 작성자는 보여주지 않도록 했어요
=> Feat/#306: 채용공지사항 기능 추가

src/components/Card/InformCard/index.test.tsx, src/components/Providers/MajorProvider/index.tsx, src/components/Providers/MajorProvider/major-storage.ts, src/components/Providers/OverlayProvider/index.tsx, src/contexts/major.ts, src/hooks/useMajor.ts, src/pages/MajorDecision/index.test.tsx
- closes : #308 
- 사용자의 전공 정보를 상태(`useState`) 로 관리할 필요는 없다고 판단해서 로컬 스토리지에 의존하는 클래스를 구현해서 관리하는 것으로 변경 했어요.
```js
interface IMajorStorage {
getMajor: () => string | null;
setMajor: (major: string) => void;
}
class MajorStorage implements IMajorStorage {
private TOKEN_KEY;
constructor(key: string) {
this.TOKEN_KEY = key;
}
getMajor() {
const major = localStorage.getItem(this.TOKEN_KEY);
return major;
}
setMajor(major: string) {
localStorage.setItem(this.TOKEN_KEY, major);
}
}
```
클래스를 사용해서 로컬 스토리지에 저장한 사용자의 전공 정보를 관리하고,
```js
const MajorProvider = ({ children }: MajorProviderProps) => {
const majorStorage = new MajorStorage(MAJOR_STORAGE_KEY);
return (
<MajorContext.Provider value={majorStorage}>
{children}
</MajorContext.Provider>
);
};
```
`MajorProvider` 컴포넌트는 해당 클래스를 의존성으로 주입해줬어요. 주입 받는 …
=> Refactor/#308: 사용자의 전공 상태 정보(useState) 삭제
