GDSC-PKNU-Official/pknu-notice-front

- docker-compose.yml
- dockerfile.dev
Docker 를 이용하여 통합된 환경에서 운영 및 배포가 가능하게 하도록 개발 시작부터 Docker 를 이용하여 환경 세팅
- Docker compose를 이용하여 간단하게 실행하는 방법
```
docker-compose up
```
- Docker 종료하는 방법
```
docker-compose down
또는
도커가 켜진 터미널에서 ctrl + c
```
- Vite를 이용한 경우 외부에서 접속을 허용하게 하려면 vite --host 0.0.0.0 을 추가하여야 함
> Config/#5: Docker를 이용하여 빌드 및 호스트에서 원격 접속 설정

- package.json
- src/components/Icon/index.tsx
- yarn.lock
- Closes: #13
- Icon 컴포넌트 구현했어요.
- 종류는 피그마에 있는것들만 있어요.
```ts
type IconKind =
| 'map'
| 'home'
| 'accountCircle'
| 'school'
| 'notification'
| 'menu'
| 'arrowBack';
```
- 타입 관리 어떻게 하면 좋을까요? 한 파일에 다 있으니까 지저분한것 같기도?
```ts
const 예시 = () => {
return (
<div>
<Icon kind="accountCircle" onClick={() => alert('마이페이지')} />
<Icon kind="home" />
<Icon kind="map" color="#71BC5C" />
<Icon kind="notification" color="gray" />
</div>
);
};
```
> Feat/#13: Icon 컴포넌트 구현

- src/components/Header/index.tsx
- Closes: #18 
- `Header` 컴포넌트 만들었어요
- Icon 컴포넌트 적용시켜서 만들려고 했는데 아직 merge 가 안된 상태라 일단 만들어진 버튼 컴포넌트 사용해서 만들어 봤어요
- 뒤로가기 버튼 제대로 되는지 테스트는 라우팅 어떻게 할건지 정해지고 나서 할게요
- 그런데, 저희 `메뉴바` 버튼 안쓰기로 했었지 않나요?
> Feat: 헤더 컴포넌트 구현

- .github/workflows/CI.yml
- dockerfile.dev
- src/components/FooterTab/index.tsx
- src/components/Header/index.tsx
- src/pages/Home/Home.test.tsx
- yarn.lock
- Closes: #17 
- Github Action 을 이용해 구현했어요
- 테스트 환경은 도커환경과, Node 16 환경 2 경우 테스트를 진행해요
- 패키지 관리를 yarn 으로 설정하다보니 sudo 권한으로 install을 진행해 보안에 취약할수도 있어요 (필요시 수정)
- 테스트 실패시 실패 사유 로그를 보기가 힘들어요 (이후 필요하다면 jest-junit 라이브러리를 이용하여 수정할 예정
> Config/#17: CI 구현

- src/App.tsx
- Closes: #26  
routing 설정에 / 빠져있던 오타 수정
> Chore: 라우팅 경로에 오타 수정

- src/components/Image/index.tsx
- src/utils/styles/size.ts
- tsconfig.path.json
- vite.config.ts
- Closes : #24 
- @types 폴더 절대경로 설정을 했어요
- 폴더이름은 @types 인데, 절대경로 이름은 @type 이에요. types 폴더 이름이 겹쳐서 일단 임시방편으로 이렇게 했어요
> Config/#24: @types 폴더 절대경로 설정

- jest.config.js
> Test: jest도 @상대경로 가능

- src/styles/ThemeProvider/theme.ts
- src/styles/emotion.d.ts
* Closes : #32 
* theme 색깔 설정을 했어요.
* ThemeProvider 를 통해서 theme props 를 넘겨줬기 때문에 어디서든 theme 색을 사용할 수 있어요.
```typescript
const Logo = styled.span`
// ...
color : ${({theme}) => theme.primary}
`;
```
> Config/#32: theme 색깔 설정

- src/styles/ThemeProvider/index.tsx
- src/styles/ThemeProvider/theme.ts
- src/styles/emotion.d.ts
* Closes: #45 
* theme 도 상수라서 상수 컨벤션에 맞춰서 변경했습니다.
```typescript
export const THEME: Theme = {
BACKGROUND: '#EAEAEA',
TEXT: {
BLACK: '#000000',
GRAY: '#808080',
WHITE: '#FFFFFF',
},
PRIMARY: '#71BC5C',
BUTTON: {
GREEN: '#71BC5C',
GRAY: '#E7E7E7',
},
MODAL_BACKGROUND: 'rgba(0, 0, 0, 0.6)',
};
```
> Chore: theme 상수 컨벤션에 맞게 변경

- jest.config.js
- Closes: #35 
- jest의 테스트환경을 더욱 확장함
- puppeteer의 경우 아직 사용에 무리가 있다 판단하여 추가하지 않음
> Chore/#35: Jest 의 testEnvironment 변경

- src/hooks/useRouter.ts
* Closes: #50 
* `useRouter` 커스텀 훅 생성했어요.
* 호출해서 `curretPath` 변수, `routerTo` 함수 사용하셔요~
> Feat: useRouter 커스텀 훅 생성

- jest.config.js
- package.json
- src/jest.setup.ts
- src/mocks/handlers.ts
- src/mocks/server.ts
- yarn.lock
- Closes: #57 
- jest로 테스트시 모킹 서버에서 데이터 가져와 테스트하도록 설정
axios를 모킹해서 사용할 수 있지만 실제 서버와 비슷하게 동작하는 MSW를 이용해 실제 응답과 비슷한 가짜 응답을 이용하여 테스트를 진행할 수 있어요
MSW 에는 2가지 방식이 있어요
- 이 방법을 이용하지 않으면 테스트 시 백엔드 서버가 안켜져있다면 통신 에러가 나요
- Mock 데이터를 이용해 request 하고 테스트 하기 위해 사용돼요
- 만약 이 방법을 쓰지 않는다면 jest 시 axios(및 fetch) 코드를 모두 무시하여 테스트를 진행하거나 직접 axios 를 모킹해서 사용해야돼요
- 주로 프론트앤드 개발 중 백엔드 개발이 늦는 경우 실제 백엔드와 통신하는것 처럼 개발하기 위해서 사용돼요
2번의 경우 추후 필요하다 생각되면 그때 넣을게요 ~
src/mocks/handlers.ts 파일을 보면 handlers 라는 배열이 있어요 아래와 같은 코드를 추가하여 해당 경로의 http 통신을 가로채서 응답하는 값을 지정해줄 수 있어요
```
rest.get('http://localhost:8080/test', (req, res, ctx) => {
return res(ctx.status(200), ctx.json({ message: 'Hello, world!' }));
}),
```
jest 설정에서 jest.setup.ts를 추가해 줬는데 이는 jest 실행 하면 테스트 진행 전에 모킹 서버를 열고, 각각 테스트마다 reset 하고, 테스트가 끝나면 모킹 서버를 종료하는 방식을 이용해요 …
> Feat/#57: MSW 적용

- .env.vault
- .gitignore
- package.json
- yarn.lock
- Closes: #55 
- 환경변수 파일 .env 파일을 공유하기 위한 dotenv vault 설정
- node, vite 의 환경변수 접근방법이 다른 문제는 따로 Issue 를 만들어서 진행할 예정
.env 파일의 경우 변수값을 은닉해야되기에 깃허브에 업로드를 하지 않아요 그래서 .env 파일을 수정한 경우 팀원들에게 직접 알려줘야하는 문제가 있어요. 그래서 .env 파일을 공유하기 위한 dotenv vault 를 만들어봤어요
[dotenv vault 공식문서 링크](https://www.dotenv.org/docs)
- 환경변수값을 공유하기 위해 클라우드 서비스를 이용해요. 하지만 환경변수에 접근하는건 인가된 사람만 접근할 수 있어요
- 최초 실행시에 먼저 인가된 사람인지 확인하기 위해 로그인 해야해요 (웹 브라우저 창에서 로그인됨)
`npx dotenv-vault login`
- 클라우드에 저장되어 있는 환경변수의 값들을 볼 수 있어요
`npx dotenv-vault open`
- .env 파일을 수정하면 아래와 같은 명령어로 업로드 할 수 있어요
`npx dotenv-vault push`
`npx dotenv-vault pull`
`npx dotenv-vault login` 하면 생성되는 파일로 본인을 인증할 수 있는 파일이에요
이전 버전의 .env 파일 내용이에요
현재 환경변수의 버전 정보를 담고 있어서 다른 팀원이 환경변수값을 변경됨을 알 수 있어요
> Feat/#55: dotenv vault 설정

- jest.config.js
- src/apis/http.ts
- src/config/index.ts
- tsconfig.path.json
- vite.config.ts
- Closes: #61 
Axios 호출을 모듈화하고 apis, config 디렉토리도 @를 이용한 절대 경로로 접근하도록 설정했어요~
> Refactor/#61: Axios로 API 호출 모듈화 

- src/components/Button/index.tsx
- src/components/Modal/MajorModal/index.tsx
- src/components/Modal/SuggestionModal/SuggestionInput.tsx
- src/components/Modal/SuggestionModal/SuggestionThxMessage.tsx
- src/components/Modal/SuggestionModal/index.tsx
- src/components/Modal/index.tsx
- src/pages/My/index.tsx
* Closes : #88 
* 사용자가 건의사항을  작성했을 때, 감사 메세지를 보여주는 기능을 구현했어요
* `SuggestionModal` 컴포넌트
* **isSended** 변수를 사용해서, 사용자가 전송 했으면 감사 메세지를 보여줘요
* 전송하지 않았으면, 입력창 컴포넌트를 보여줘요 
* `Modal` 컴포넌트 스타일 추상화
* `Modal` 컴포넌트에는 공통된 스타일 속성이 많은데, Modal을 호출할 때 마다 공통된 스타일 속성을 스타일 컴포넌트로 만들어서 전달하는게 비효율적인 코드 반복이라고 느껴졌어요.
* `Modal` 컴포넌트 내부에서 반복적으로 사용되는 스타일을 추상화 했어요.
* 건의사항 전송은 5글자 이상으로
* 단어 하나만 건의사항으로 받을 수 있는 경우도 생길 것 같아서 일단 5글자 이상만 전송할 수 있도록 했어요.
* 감사 메세지는 구현 했지만, 사용자에게 입력한 내용이 맞는지 확실하게 재확인 하는 로직이 필요한지에 대해서 고민이 되네요. **의견 코멘트로 부탁드립니다!**
https://github.com/hwinkr/algorithm/assets/68489467/f96d1ba5-0b5b-4695-9580-348a8383f114
> Feat/#88: 건의사항 작성시 감사 메세지 구현

- src/config/index.ts
- Closes: #94 
- 백엔드 URL 주소를 변경했어요!
> Fix: 서버 주소 변경

- src/App.tsx
- src/components/FooterTab/index.tsx
- src/components/Header/index.tsx
- closes: #114 
- position fixed 로 변경하고 콘텐츠가 헤더와 푸터로 비치지 않도록 만들었어요!
> Style/#114: Header, Footer 크기 변경

- src/App.tsx
> Fix: 누락된 코드 추가

- src/mocks/handlers/announceHandlers.ts
- src/pages/Announcement/index.tsx
> Fix: undefined 삭제

- src/App.tsx
- src/mocks/handlers/announceHandlers.ts
- src/pages/Announcement/index.tsx
> 부리미 0.17v 배포

- src/apis/Suspense/fetch-announce-list.ts
- src/mocks/handlers/announceHandlers.ts
- src/pages/Announcement/index.tsx
* `undefined` 에서, `''`로 api 호출
> 부리미 0.18v 배포

- vite.config.ts
- closes: #140 
- PWA 세로모드 및 디바이스에서 풀 스크린으로 동작하도록 수정했어요!
> Fix: PWA 세로모드 고정, 디바이스의 풀 스크린으로 동작하도록 수정

- index.html
* Closes: #146 
* viewport height 고정해요
> Fix: viewport height 고정

- index.html
- src/components/Card/AnnounceCard/index.tsx
> 부리미 v0.22 배포

- src/pages/Home/index.tsx
> Fix: 잘못된 코드 수정

- public/manifest.json
- public/mockServiceWorker.js
- public/serviceWorker.js
- vite.config.ts
- closes: #169 
- 일단 PWA 안되는 문제 해결해볼게요
> Fix/#169: PWA 적용 안되는 문제 해결해보기

- index.html
- public/manifest.json
> Fix/#169: manifest.json 경로 추가

- package.json
- public/mockServiceWorker.js
- public/serviceWorker.js
- src/main.tsx
- closes: #174
- 개발환경에만 MSW가 서비스워커에 등록되도록 수정했어요
> Fix/#174: 개발환경에만 MSW가 서비스워커에 등록되도록 수정

- src/App.tsx
- src/config/index.ts
- src/utils/routeChangeTracker.ts
- closes: #168 
- 구글 애널리틱스 붙였어요
- 총 몇명의 유저가 접속했고, 어느 페이지를 몇번 갔는지 확인할 수 있어요!
- 구글 애널리틱스의 기능은 따로 공부해야할 정도로 많은데 일단 기본 기능만 넣어도 충분한거 같아요
> Feat/#168: 구글 애널리틱스 붙이기

- public/.well-known/assetlinks.json
- closes: #181 
- 스토어에 필요한 파일을 추가했어요!
> Feat: 스토어 배포에 필요한 파일 추가

- public/privacy.html
- closes: #183 
- 개인정보처리방침 추가했어요
> Feat: 개인정보처리방침 추가

- src/components/Header/index.tsx
- closes: #186 
- 헤더의 햄버거바를 삭제했어요
> Fix: 햄버거바 삭제

- public/privacy.html
- 개인정보처리방침 html 파일의 인코딩방식을 utf-8 로 설정해줬어요
> Fix: 문자를 UTF-8 로 인코딩하도록 변경

- README.md
> Docs: 부림이 프론트 리드미 작성

- README.md
> Docs: 부림이 프론트 레파지토리 리드미 작성

- src/pages/Announcement/index.tsx
- closes : #229 
- 사용자에게 `학과 공지사항`에 대한 푸쉬 알림이 오면 학교가 아닌 학과 공지사항 페이지로 바로 이동하게 되는데 이 때, bottom-bar 위치가 학교 공지사항에 그대로 있는 문제를 해결했어요
- css 가상요소를 사용해서 해결 했어요~
```css
&:before {
content: '';
position: absolute;
bottom: 0;
left: ${({ isActiveSchool }) => (isActiveSchool ? '0' : '50%')};
width: 50%;
height: 3px;
background-color: ${THEME.PRIMARY};
transition: left 0.3s ease-in-out;
}
```
> fix/#229 : 학과 공지사항 페이지로 바로 이동했을 경우, bottom-bar 위치 에러 해결

- src/components/Card/AnnounceCard/index.tsx
- src/components/List/CollegeList/CollegeItem.tsx
- src/components/List/DepartmentList/DepartmentItem.tsx
- src/pages/Home/index.tsx
- closes: #231
- 공지사항 리스트 클릭 애니메이션 추가했어요
- 단과대/학과선택 리스트의 클릭 애니메이션 추가했어요
https://github.com/GDSC-PKNU-21-22/pknu-notice-front/assets/71641127/573d0a1c-7948-4adc-bd57-e4caeddf759f
> Feat/#231: 공지사항 리스트, 단과대/학과 선택 리스트 클릭 애니메이션 추가

- src/styles/Global/index.tsx
- src/styles/ThemeProvider/theme.ts
- closes: #209 
- 배경색 기본색으로 롤백했어요
> fix: 배경색 기본색으로 롤백

- src/components/Carousel/index.tsx
- src/mocks/handlers/announceHandlers.ts
- closes: #235 
- whalebe 엔드포인트 오타 수정했어요
> Fix: whalebe 엔드포인트 오타 수정

- src/components/Carousel/index.tsx
- src/pages/Home/index.tsx
- closes: #238 
- 캐러셀에 있는 버튼의 위치를 고정된 위치로 수정했어요
- 캐러셀 아래에 마진을 추가했어요
- 모집기간 크기를 조금 줄였어요
> Fix/#238: 캐러셀 일부 수정

- src/components/Card/InformCard/index.tsx
> Fix: 공지사항 카드 글자색 검은색으로 롤백

- public/.well-known/apple-app-site-association
- https://lxxyeon.tistory.com/74 해당 글을 참고하여 app store로 받은 부림이에서 universal link 가 되는지 확인하려고해요!
> Feat: aasa 파일 추가

- public/.well-known/assetlinks.json
- src/pages/My/index.tsx
> 부림이 v0.37 배포

- index.html
- closes: #265 
- 타이틀을 vite + react + ts 에서 부림이로 변경했어요
> Config: 타이틀 변경

- README.md
> 부림이 v0.4.2 배포 
